{
	"htmlTemplate" : null,
	"conversation" : [
		{"from": "_Tempo", "message" : "Hey, babe"},
		{"from": "_Partner", "message" : "Hey :)"},
		{"from": "_Partner", "message" : "I miss you"},
		{"from": "_Tempo", "message" : "I know :("},
		{"from": "_Tempo", "message" : "I miss you too"},
		{"from": "_Tempo", "message" : "You are destroying my sleep schedule"},
		{"from": "_Partner", "message" : "Haha don't act like this is a one way street"},
		{"from": "_Partner", "message" : "You have me staying up til 3"},
		{"from": "_Partner", "message" : "Timezones suck, we should abolish them" },
		{"from": "_Tempo", "message" : "I'm sure that would work out just fine haha"},
		{"from": "_Partner", "message" : "How are things at work?" },
		{"from": "_Tempo", "message" : "They're going really well"},
		{"from": "_Tempo", "message" : "Thats actually why I hit you up"},
		{"from": "_Tempo", "message" : "Guess who is in charge of a new project :)"},
		{"from": "_Partner", "message" : "No way!!! Congrats"},
		{"from": "_Tempo", "message" : "Its nothing super big, just some marketing stuff"},
		{"from": "_Tempo", "message" : "We're just training Sesh@ for food advertising"},
		{"from": "_Tempo", "message" : "It's actually a pretty decent contract!"},
		{"from": "_Tempo", "message" : "I mean it's nothing too crazy, I'm not working on the big stuff but it's still exciting"},
		{"from": "_Partner", "message" : "I'm proud of you babe :)"},
		{"from": "_Partner", "message" : "Do you think this means Qualia is thinking of offering you a job?"},
		{"from": "_Tempo", "message" : "I don't know, I don't want to get my hopes up too high but they also don't really put interns in charge of projects"},
		{"from": "_Partner", "message" : "Look at you, big girl on the block"},
		{"from": "_Tempo", "message" : "I hope we can get Sesh@ to work for the contract"},
		{"from": "_Tempo", "message" : "Fingers crossed, if this works out maybe they might bring me on full time, working on real projects"},
		{"from": "_Partner", "message" : "I'm so happy for you babe :)"},
		{"from": "_Partner", "message" : "I'm sorry, but I'm really tired though"},
		{"from": "_Partner", "message" : "I think I'm heading to bed, I'll call you in the morning. Goodnight <3"},
		{"from": "_Tempo", "message" : "Don't apologize babe, I appreciate you staying up for me"},
		{"from": "_Tempo", "message" : "Goodnight! I love you <3"},
		{"from": "_Partner", "message" : "Love you too"},

	]
}
